functions_csv = "data/RedCarpet-S_functions.csv"
build_target = "RedCarpet-S"

[decomp_me]
compiler_name = "clang-8.0.0"
default_compile_flags = "-x c++ -O3 -g2 -std=c++17 -fno-rtti -fno-exceptions -Wall -Wextra -fno-strict-aliasing"
